name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action
      - run: nix-build
      - run: nix-shell --run "npm run test"
